version: '2'
services:
  salt:
    hostname: salt
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/master/
    ports:
      - "8000:8000"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./saltstack/salt:/srv/salt
      - ./saltstack/pillar:/srv/pillar
    networks:
      - salt
  minion1:
    hostname: minion1
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/minion1/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - salt
  minion2:
    hostname: minion2
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/minion2/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - salt
  vault:
    image: vault:0.9.6
    ports:
    - "8200:8200"
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: mysecret
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    networks:
      - salt
  squid:
    image: datadog/squid
    networks:
      - salt
networks:
  salt:
